.POSIX:

CC = arm-none-eabi-gcc
CXX = arm-none-eabi-gcc
CFLAGS += -O1 -std=c99 -mcpu=cortex-m0plus -mthumb
CFLAGS += -DTARGET_LPC11U68
CFLAGS += -D__MBED__=1
CFLAGS += -DDEVICE_I2CSLAVE=1
CFLAGS += -DTARGET_LIKE_MBED
CFLAGS += -DTARGET_NXP
CFLAGS += -D__MBED_CMSIS_RTOS_CM
CFLAGS += -DDEVICE_RTC=1
CFLAGS += -DTOOLCHAIN_object
CFLAGS += -D__CMSIS_RTOS
CFLAGS += -DTOOLCHAIN_GCC
CFLAGS += -DTARGET_CORTEX_M
CFLAGS += -DTARGET_M0P
CFLAGS += -DTARGET_UVISOR_UNSUPPORTED
CFLAGS += -DDEVICE_SERIAL=1
CFLAGS += -DDEVICE_INTERRUPTIN=1
CFLAGS += -DTARGET_LPCTarget
CFLAGS += -DTARGET_CORTEX
CFLAGS += -DDEVICE_I2C=1
CFLAGS += -D__CORTEX_M0PLUS
CFLAGS += -DTARGET_FF_ARDUINO
CFLAGS += -DTARGET_RELEASE
CFLAGS += -DMBED_BUILD_TIMESTAMP=1526394586.66
CFLAGS += -DARM_MATH_CM0PLUS
CFLAGS += -DTARGET_LPC11U6X
CFLAGS += -DDEVICE_SLEEP=1
CFLAGS += -DTOOLCHAIN_GCC_ARM
CFLAGS += -DDEVICE_SPI=1
CFLAGS += -DDEVICE_ANALOGIN=1
CFLAGS += -DDEVICE_PWMOUT=1
CFLAGS += -DTARGET_LIKE_CORTEX_M0

CPPFLAGS += -O1 -std=c++17 -mcpu=cortex-m0plus -mthumb
CPPFLAGS += -fno-rtti
CPPFLAGS += -Wvla
CPPFLAGS += -DTARGET_LPC11U68
CPPFLAGS += -D__MBED__=1
CPPFLAGS += -DDEVICE_I2CSLAVE=1
CPPFLAGS += -DTARGET_LIKE_MBED
CPPFLAGS += -DTARGET_NXP
CPPFLAGS += -D__MBED_CMSIS_RTOS_CM
CPPFLAGS += -DDEVICE_RTC=1
CPPFLAGS += -DTOOLCHAIN_object
CPPFLAGS += -D__CMSIS_RTOS
CPPFLAGS += -DTOOLCHAIN_GCC
CPPFLAGS += -DTARGET_CORTEX_M
CPPFLAGS += -DTARGET_M0P
CPPFLAGS += -DTARGET_UVISOR_UNSUPPORTED
CPPFLAGS += -DDEVICE_SERIAL=1
CPPFLAGS += -DDEVICE_INTERRUPTIN=1
CPPFLAGS += -DTARGET_LPCTarget
CPPFLAGS += -DTARGET_CORTEX
CPPFLAGS += -DDEVICE_I2C=1
CPPFLAGS += -D__CORTEX_M0PLUS
CPPFLAGS += -DTARGET_FF_ARDUINO
CPPFLAGS += -DTARGET_RELEASE
CPPFLAGS += -DMBED_BUILD_TIMESTAMP=1526394586.66
CPPFLAGS += -DARM_MATH_CM0PLUS
CPPFLAGS += -DTARGET_LPC11U6X
CPPFLAGS += -DDEVICE_SLEEP=1
CPPFLAGS += -DTOOLCHAIN_GCC_ARM
CPPFLAGS += -DDEVICE_SPI=1
CPPFLAGS += -DDEVICE_ANALOGIN=1
CPPFLAGS += -DDEVICE_PWMOUT=1
CPPFLAGS += -DTARGET_LIKE_CORTEX_M0

OBJCOPY = arm-none-eabi-objcopy
LDFLAGS = -L. -lpokitto -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -T LPC11U68.ld
LDFLAGS += -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_memalign_r -Wl,-n --specs=nano.specs -mcpu=cortex-m0plus -mthumb


OBJS = main.o sprites.o game.o trail.o

all: gamejarm2021.bin

.elf.bin:
	$(OBJCOPY) -O binary $< $@

.SUFFIXES: .elf .bin

gamejarm2021.elf: $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS)

main.o: maps.h sprites.h Smile.h
game.o: game.h trail.h
trail.o: trail.h
